### ISSUE TITLE
Charm fails on arm64

### ISSUE THREAD

**Issue by morphis** [canonical/charm-lxd#33]
Trying out the charm this morning on an m6g.large (arm64) on AWS gives me

```
unit-lxd-0: 09:21:42 ERROR juju.worker.uniter.operation hook "local-storage-attached" (via hook dispatching script: dispatch) failed: exit status 1
unit-lxd-0: 09:21:42 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
unit-lxd-0: 09:21:52 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached Traceback (most recent call last):
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached   File "./src/charm.py", line 17, in <module>
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached     import pylxd
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached   File "/var/lib/juju/agents/unit-lxd-0/charm/venv/pylxd/__init__.py", line 17, in <module>
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached     from pylxd.client import Client, EventType
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached   File "/var/lib/juju/agents/unit-lxd-0/charm/venv/pylxd/client.py", line 23, in <module>
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached     from cryptography import x509
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached   File "/var/lib/juju/agents/unit-lxd-0/charm/venv/cryptography/x509/__init__.py", line 6, in <module>
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached     from cryptography.x509 import certificate_transparency
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached   File "/var/lib/juju/agents/unit-lxd-0/charm/venv/cryptography/x509/certificate_transparency.py", line 10, in <module>
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached     from cryptography.hazmat.bindings._rust import x509 as rust_x509
unit-lxd-0: 09:21:52 WARNING unit.lxd/0.local-storage-attached ImportError: /var/lib/juju/agents/unit-lxd-0/charm/venv/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory
unit-lxd-0: 09:21:53 ERROR juju.worker.uniter.operation hook "local-storage-attached" (via hook dispatching script: dispatch) failed: exit status 1
unit-lxd-0: 09:21:53 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
```

This is using revision 28 from the charmhub.

**Comment by simondeziel** [comment]
Revision 28 is supposed to be for `amd64`, not `arm64`:

```
$ charmcraft status lxd
Track    Base                    Channel    Version    Revision
latest   ubuntu 20.04 (amd64)    stable     28         28
                                 candidate  ↑          ↑ 
                                 beta       ↑          ↑
                                 edge       28         28
         ubuntu 20.04 (arm64)    stable     29         29
                                 candidate  ↑          ↑ 
                                 beta       ↑          ↑
                                 edge       29         29
         ubuntu 20.04 (armhf)    stable     31         31
                                 candidate  ↑          ↑ 
                                 beta       ↑          ↑
                                 edge       31         31
         ubuntu 20.04 (ppc64el)  stable     30         30
                                 candidate  ↑          ↑
                                 beta       ↑          ↑
                                 edge       30         30
         ubuntu 20.04 (s390x)    stable     27         27
                                 candidate  ↑          ↑
                                 beta       ↑          ↑
                                 edge       27         27
```

I was able to test revision 29 on `arm64` after telling Juju I wanted an `arm64` machine with: `juju set-model-constraints arch=arm64`.

**Comment by stgraber** [comment]
Closing as our stuff seems to be properly built (on Launchpad) and published to the store.
It seems like there may be a Juju bug where it incorrectly selects the wrong architecture?

@simondeziel mentioned getting rev 27 (s390x) earlier too which makes absolutely no sense...
